### ISSUE TITLE
UnitOpenGLImagePNG + UnitOpenGLImageJPEG issues with freepascal

### ISSUE THREAD

**Issue by JernejL** [BeRo1985/pasgltf#1]
This unit does not compile under freepascal 3.0.4: 
UnitOpenGLImagePNG.pas(259,9) Error: ENDIF without IF(N)DEF 
 
Working around that, compilation later fails at UnitOpenGLImageJPEG:
UnitOpenGLImageJPEG.pas(237,16) Error: Identifier not found "TFPReaderJPEG"

**Comment by JernejL** [comment]
I got it to compile in freepascal by working around the 2 problems (commented out openglimagejpeg) and it runs, but it's unable to load any gltf files, it always raises EPasGLTFInvalidDocument exception and then dies in main loop here: 
 
EAccessViolation: Access violation
  $004045B5  MAINLOOP,  line 1014 of PasGLTFViewer.dpr
  $004058DE  main,  line 1440 of PasGLTFViewer.dpr

**Comment by BeRo1985** [comment]
fixed
